### ISSUE TITLE
Native and Rosbridge Connections (ROS 1 and 2): Support reading and setting ROS params

### ISSUE THREAD

**Issue by esthersweon** [foxglove/studio#1662]
Studio users connected to a data source via a native or Rosbridge connection (ROS 1 or 2) should be able to:
- Receive and read ROS params from their ROS stack
- Set ROS params by sending values back to the stack

**Comment by amacneil** [comment]
@esthersweon can you please split this ticket up into separate tickets for each data source that is missing params support?

Is there anywhere in our docs that tells you which data sources support params?

**Comment by jhurliman** [comment]
This should be working in ROS1 native and rosbridge. ROS2 native param support is being tracked in https://github.com/foxglove/studio/issues/2614

**Comment by chenjunnn** [comment]
> This should be working in ROS1 native and rosbridge.

@jhurliman I'm using rosbridge connection and open the `Parameter` panel, but it still shows `Connect to a ROS source to view parameters`. And I cound not find related PRs or commits. Is this feature not supported in the current version? If so, I would appreciate it if you could tell me that when it would be supported.

**Comment by jtbandes** [comment]
Params are supported in ROS 1 native connections since https://github.com/foxglove/studio/pull/601, but not currently in rosbridge connections.

**Comment by amacneil** [comment]
@esthersweon maybe somewhere in our docs we could have a matrix of which features are supported by which data sources?
