### ISSUE TITLE
New3D orientation breaks when seeking in nuScenes dataset

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#3790]
When seeking around in the example dataset, the camera orientation seems to break so what was previously up is no longer up:

https://user-images.githubusercontent.com/14237/177857135-518abdbf-c3ce-48e6-881d-aafd1aa1fd37.mov

**Comment by jhurliman** [comment]
I think this is fixed in https://github.com/foxglove/studio/pull/3773

**Comment by jtbandes** [comment]
I can still reproduce it on the current version of studio.foxglove.dev
