### ISSUE TITLE
Inconsistent font size in data source sidebar

### ISSUE THREAD

**Issue by jtbandes** [foxglove/studio#4130]
Font sizes are inconsistent for start/end time and duration in the "Data source" sidebar:

<img width="154" alt="image" src="https://user-images.githubusercontent.com/14237/184696240-bfd88398-8ff2-4608-ac06-78b48db9ba13.png">

- Version: latest web
- OS: macOS Chrome
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): local mcap file

**Comment by jtbandes** [comment]
Note that sometimes the font family also differs. Maybe some styles are not getting applied depending on the order they change in. Perhaps a precedence issue with our style libraries

**Comment by foxymiles** [comment]
Fixed in https://github.com/foxglove/studio/pull/4273

**Comment by jtbandes** [comment]
Still occurs on main:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/14237/187986255-c11c1795-530a-427b-8f0b-8504c0625d2f.png">

**Comment by foxymiles** [comment]
@jtbandes Do you have any repro steps? I'm not seeing it here.

**Comment by jtbandes** [comment]
Seems to only happen when the start time is shown as a duration. Try this file:

[arrows.mcap.zip](https://github.com/foxglove/studio/files/9473795/arrows.mcap.zip)

By the way, it seems like a bug that we show the start time as 0.0 but the end time as a date in 1969.

**Comment by osaro-imohe** [comment]
My pending PR resolves this issue.

**Comment by foxymiles** [comment]
Closed by https://github.com/foxglove/studio/pull/4346
